sudo: false

language: node_js
node_js:
  "9.11.1"

cache:
  directories:
    - test/elm-stuff/build-artifacts
    - node_modules

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.19.0

before_install:
  - npm i -g npm@^5.6.0

install:
  - npm install

script:
  - npm test
  - npm run approve
