sudo: false

language: node_js
node_js:
  "lts/*"

cache:
  directories:
    - elm-stuff/

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.19.0

before_install:
  - npm i -g npm@lts

install:
  - npm ci

script:
  - npm test
  - npm run approve
